version: '2'

services:

  main:
    build: main
    volumes:
     - ${HOME}:/home/notroot/ext
     - /tmp/.X11-unix:/tmp/.X11-unix
     - ${HOME}/.Xauthority:/home/notroot/.Xauthority
     - ${XDG_RUNTIME_DIR}:/run/xdg-runtime-dir
     - /dev/bus/usb:/dev/bus/usb
     - /run/udev:/run/udev:ro
    privileged: true
    environment:
     - DISPLAY
     - XDG_RUNTIME_DIR=/run/xdg-runtime-dir
     - UID=${UID}
    restart: "no"
    network_mode: "host"
